questions = {
    "easy": [
        {"question": "What is the capital of France?",
         "options": ["A. Berlin", "B. Paris", "C. Rome", "D. Madrid"], "answer": "B"},
        {"question": "Which planet is the Red Planet?",
         "options": ["A. Venus", "B. Jupiter", "C. Mars", "D. Saturn"], "answer": "C"},
        {"question": "How many continents are there?",
         "options": ["A. 5", "B. 6", "C. 8", "D. 7"], "answer": "D"},
        {"question": "What is 12 x 12?",
         "options": ["A. 124", "B. 144", "C. 134", "D. 154"], "answer": "B"},
        {"question": "Which language is used for web styling?",
         "options": ["A. Python", "B. Java", "C. CSS", "D. C++"], "answer": "C"},
    ],
    "medium": [
        {"question": "What does CPU stand for?",
         "options": ["A. Central Process Unit", "B. Central Processing Unit", "C. Computer Personal Unit", "D. Core Processing Unit"], "answer": "B"},
        {"question": "Which data structure uses LIFO?",
         "options": ["A. Queue", "B. Array", "C. Stack", "D. LinkedList"], "answer": "C"},
        {"question": "What is 2**10 in Python?",
         "options": ["A. 20", "B. 512", "C. 1024", "D. 2048"], "answer": "C"},
        {"question": "Who invented the telephone?",
         "options": ["A. Edison", "B. Tesla", "C. Bell", "D. Newton"], "answer": "C"},
        {"question": "Which gas do plants absorb?",
         "options": ["A. Oxygen", "B. Nitrogen", "C. Carbon Dioxide", "D. Hydrogen"], "answer": "C"},
    ],
    "hard": [
        {"question": "Time complexity of Binary Search?",
         "options": ["A. O(n)", "B. O(n²)", "C. O(log n)", "D. O(1)"], "answer": "C"},
        {"question": "Which keyword creates a generator in Python?",
         "options": ["A. return", "B. yield", "C. generate", "D. async"], "answer": "B"},
        {"question": "What does SQL stand for?",
         "options": ["A. Structured Query Language", "B. Simple Query Logic", "C. Sequential Query Language", "D. Standard Query List"], "answer": "A"},
        {"question": "Best average case sorting algorithm O(n log n)?",
         "options": ["A. Bubble Sort", "B. Selection Sort", "C. Merge Sort", "D. Insertion Sort"], "answer": "C"},
        {"question": "Value of Pi to 4 decimal places?",
         "options": ["A. 3.1416", "B. 3.1214", "C. 3.1618", "D. 3.1415"], "answer": "D"},
    ]
}